import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { rootDirectory } from "./release-utils.mjs";

function write(filePath, contents) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, contents);
}

function createFixture({ validCargoTarget = true } = {}) {
  const fixture = fs.mkdtempSync(path.join(os.tmpdir(), "modelcrew-version-set-"));

  fs.mkdirSync(path.join(fixture, "scripts"), { recursive: true });
  for (const fileName of ["set-version.mjs", "release-utils.mjs"]) {
    fs.copyFileSync(
      path.join(rootDirectory, "scripts", fileName),
      path.join(fixture, "scripts", fileName),
    );
  }

  write(
    path.join(fixture, "package.json"),
    `${JSON.stringify({ name: "modelcrew-desktop", version: "0.0.1" }, null, 2)}\n`,
  );
  write(
    path.join(fixture, "package-lock.json"),
    `${JSON.stringify(
      {
        name: "modelcrew-desktop",
        version: "0.0.1",
        lockfileVersion: 3,
        packages: { "": { name: "modelcrew-desktop", version: "0.0.1" } },
      },
      null,
      2,
    )}\n`,
  );
  write(
    path.join(fixture, "src-tauri", "Cargo.toml"),
    `[package]\nname = "modelcrew-desktop"\nversion = "0.0.1"\nedition = "2021"\n`,
  );
  write(
    path.join(fixture, "src-tauri", "Cargo.lock"),
    `# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = "modelcrew-desktop"\nversion = "0.0.1"\n`,
  );
  if (validCargoTarget) {
    write(path.join(fixture, "src-tauri", "src", "lib.rs"), "");
  }
  write(
    path.join(fixture, "CHANGELOG.md"),
    "# Changelog\n\n## 0.0.1\n\n### Русский\n\nРелиз.\n\n- Изменение\n\n### English\n\nRelease.\n\n- Change\n",
  );
  fs.mkdirSync(path.join(fixture, "release-notes"), { recursive: true });

  return fixture;
}

function runVersionSet(fixture, version) {
  return spawnSync(process.execPath, [path.join(fixture, "scripts", "set-version.mjs"), version], {
    cwd: fixture,
    encoding: "utf8",
  });
}

test("set-version synchronizes package and Cargo versions and creates templates", () => {
  const fixture = createFixture();

  try {
    const result = runVersionSet(fixture, "0.0.2");
    assert.equal(result.status, 0, result.stderr);

    const packageJson = JSON.parse(fs.readFileSync(path.join(fixture, "package.json"), "utf8"));
    const packageLock = JSON.parse(
      fs.readFileSync(path.join(fixture, "package-lock.json"), "utf8"),
    );
    const cargoManifest = fs.readFileSync(
      path.join(fixture, "src-tauri", "Cargo.toml"),
      "utf8",
    );
    const cargoLock = fs.readFileSync(path.join(fixture, "src-tauri", "Cargo.lock"), "utf8");
    const releaseNote = JSON.parse(
      fs.readFileSync(path.join(fixture, "release-notes", "0.0.2.json"), "utf8"),
    );
    const changelog = fs.readFileSync(path.join(fixture, "CHANGELOG.md"), "utf8");

    assert.equal(packageJson.version, "0.0.2");
    assert.equal(packageLock.version, "0.0.2");
    assert.equal(packageLock.packages[""].version, "0.0.2");
    assert.match(cargoManifest, /^version = "0\.0\.2"$/m);
    assert.match(cargoLock, /name = "modelcrew-desktop"\nversion = "0\.0\.2"/);
    assert.equal(releaseNote.version, "0.0.2");
    assert.match(releaseNote.ru.title, /__REPLACE_ME/);
    assert.ok(changelog.indexOf("## 0.0.2") < changelog.indexOf("## 0.0.1"));
  } finally {
    fs.rmSync(fixture, { recursive: true, force: true });
  }
});

test("set-version restores every edited file when Cargo validation fails", () => {
  const fixture = createFixture({ validCargoTarget: false });
  const trackedFiles = [
    "package.json",
    "package-lock.json",
    "src-tauri/Cargo.toml",
    "src-tauri/Cargo.lock",
    "CHANGELOG.md",
  ];
  const before = new Map(
    trackedFiles.map((fileName) => [fileName, fs.readFileSync(path.join(fixture, fileName), "utf8")]),
  );

  try {
    const result = runVersionSet(fixture, "0.0.2");
    assert.notEqual(result.status, 0);

    for (const [fileName, contents] of before) {
      assert.equal(fs.readFileSync(path.join(fixture, fileName), "utf8"), contents);
    }
    assert.equal(fs.existsSync(path.join(fixture, "release-notes", "0.0.2.json")), false);
  } finally {
    fs.rmSync(fixture, { recursive: true, force: true });
  }
});
