// Единственный шлюз, который не даёт выпустить сборку без политики
// безопасности содержимого, с рассинхронизированными версиями или с откатом
// версии назад. Опасен здесь не отказ, а «молча пропустили», поэтому каждый
// тест смотрит на код выхода дочернего процесса: скрипт бросает исключение и
// падает, а не возвращает список ошибок.
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const validateRelease = path.join(root, "scripts", "release", "validate-release.mjs");
const shippedConfig = JSON.parse(
  fs.readFileSync(path.join(root, "src-tauri", "tauri.conf.json"), "utf8"),
);
const shippedCsp = shippedConfig.app.security.csp;

const VERSION = "0.1.0";
const PACKAGE_NAME = "modelcrew-desktop";

function write(filePath, contents) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, contents, "utf8");
}

function workspace() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "modelcrew-validate-release-"));
  test.after(() => fs.rmSync(dir, { recursive: true, force: true }));
  return dir;
}

function releaseNotes(version) {
  return {
    version,
    ru: { title: "Релиз", summary: "Краткое описание", highlights: ["Изменение"] },
    en: { title: "Release", summary: "Short description", highlights: ["Change"] },
  };
}

function changelog(version, { ru = true, en = true, body = "Описание." } = {}) {
  const headings = [ru ? "### Русский\n\nРелиз.\n" : "", en ? "### English\n\nRelease.\n" : ""]
    .filter(Boolean)
    .join("\n");
  // Вторая секция нужна всегда: она проверяет, что разбор CHANGELOG.md
  // останавливается на границе версии и не подхватывает чужие заголовки.
  const previous =
    version === "0.0.1"
      ? ""
      : "\n## 0.0.1\n\n### Русский\n\nПервый релиз.\n\n### English\n\nFirst release.\n";
  return `# Changelog\n\n## ${version}\n\n${body}\n\n${headings}${previous}`;
}

// Минимальный корень релиза: ровно те файлы, которые читает валидатор.
function createFixture({
  version = VERSION,
  packageName = PACKAGE_NAME,
  lockVersion = version,
  lockPackageVersion = version,
  cargoToml = `[package]\nname = "${packageName}"\nversion = "${version}"\nedition = "2021"\n`,
  cargoLock = `# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = "${packageName}"\nversion = "${version}"\n`,
  tauriVersion = "../package.json",
  security = { csp: shippedCsp },
  notes = releaseNotes(version),
  changelogText = changelog(version),
} = {}) {
  const fixture = workspace();

  write(
    path.join(fixture, "package.json"),
    `${JSON.stringify({ name: packageName, version }, null, 2)}\n`,
  );
  write(
    path.join(fixture, "package-lock.json"),
    `${JSON.stringify(
      {
        name: packageName,
        version: lockVersion,
        lockfileVersion: 3,
        packages: { "": { name: packageName, version: lockPackageVersion } },
      },
      null,
      2,
    )}\n`,
  );
  write(path.join(fixture, "src-tauri", "Cargo.toml"), cargoToml);
  write(path.join(fixture, "src-tauri", "Cargo.lock"), cargoLock);
  write(
    path.join(fixture, "src-tauri", "tauri.conf.json"),
    `${JSON.stringify(
      {
        productName: "ModelCrew",
        version: tauriVersion,
        identifier: "com.modelcrew.desktop",
        app: { security },
        plugins: { updater: { endpoints: ["https://example.invalid/latest.json"] } },
      },
      null,
      2,
    )}\n`,
  );
  if (notes !== null) {
    write(
      path.join(fixture, "release-notes", `${version}.json`),
      `${JSON.stringify(notes, null, 2)}\n`,
    );
  }
  if (changelogText !== null) {
    write(path.join(fixture, "CHANGELOG.md"), changelogText);
  }

  return fixture;
}

function run(fixture, extraArgs = []) {
  return spawnSync(process.execPath, [validateRelease, "--root", fixture, ...extraArgs], {
    encoding: "utf8",
  });
}

function runFixture(overrides = {}, extraArgs = []) {
  return run(createFixture(overrides), extraArgs);
}

function expectFailure(result, pattern) {
  assert.notEqual(result.status, 0, `validation passed: ${result.stdout}`);
  assert.doesNotMatch(result.stdout, /Release metadata is valid/u);
  assert.match(result.stderr, pattern);
}

function expectSuccess(result) {
  assert.equal(result.status, 0, result.stderr);
  assert.match(result.stdout, /Release metadata is valid/u);
}

test("a coherent release root passes and prints the released version", () => {
  const result = runFixture({}, ["--tag", `v${VERSION}`, "--latest-tag", "v0.0.9"]);

  expectSuccess(result);
  assert.match(result.stdout, /Release metadata is valid for 0\.1\.0/u);
});

test("a release without app.security.csp is rejected", () => {
  expectFailure(
    runFixture({ security: { devCsp: "default-src 'self'" } }),
    /app\.security\.csp must be set/u,
  );
});

test("an empty csp is rejected", () => {
  expectFailure(runFixture({ security: { csp: "" } }), /app\.security\.csp must be set/u);
});

test("a whitespace-only csp is rejected", () => {
  expectFailure(runFixture({ security: { csp: "   \n\t " } }), /app\.security\.csp must be set/u);
});

test("a non-string csp is rejected", () => {
  // Массив директив выглядит правдоподобно, но Tauri его не применит —
  // сборка уехала бы вообще без политики.
  expectFailure(
    runFixture({ security: { csp: ["default-src 'self'"] } }),
    /app\.security\.csp must be set/u,
  );
});

test("script-src with 'unsafe-inline' is rejected", () => {
  expectFailure(
    runFixture({
      security: { csp: "default-src 'self'; script-src 'self' 'unsafe-inline'; object-src 'none'" },
    }),
    /csp script-src must not allow 'unsafe-inline'/u,
  );
});

test("script-src with 'unsafe-eval' is rejected", () => {
  expectFailure(
    runFixture({
      security: { csp: "default-src 'self'; script-src 'self' 'unsafe-eval'; object-src 'none'" },
    }),
    /csp script-src must not allow 'unsafe-eval'/u,
  );
});

test("object-src with a wildcard is rejected", () => {
  expectFailure(
    runFixture({
      security: { csp: "default-src 'self'; script-src 'self'; object-src *" },
    }),
    /csp object-src must not allow \*/u,
  );
});

test("a csp without default-src is rejected", () => {
  expectFailure(
    runFixture({
      security: { csp: "script-src 'self'; object-src 'none'; base-uri 'self'" },
    }),
    /csp must set default-src/u,
  );
});

test("'unsafe-inline' limited to style-src still passes", () => {
  // Осознанное послабление: инлайновые стили нужны интерфейсу, инлайновые
  // скрипты — нет. Тест держит границу, чтобы правило не «починили» в
  // ложную тревогу и не начали её обходить.
  const result = runFixture({
    security: {
      csp: "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; object-src 'none'",
    },
  });

  expectSuccess(result);
  assert.match(shippedCsp, /style-src[^;]*'unsafe-inline'/u);
  assert.doesNotMatch(shippedCsp, /script-src[^;]*'unsafe-(?:inline|eval)'/u);
});

test("the shipped policy passes the gate that protects it", () => {
  expectSuccess(runFixture({ security: { csp: shippedCsp } }));
});

test("a dev-only policy with 'unsafe-eval' does not block a release", () => {
  // Проверяется только выпускаемая политика: devCsp нужен HMR и наружу не
  // уезжает. Закрепляем границу, чтобы её не перепутали в обе стороны.
  const result = runFixture({
    security: {
      csp: shippedCsp,
      devCsp: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'",
    },
  });

  expectSuccess(result);
  assert.match(shippedConfig.app.security.devCsp, /'unsafe-eval'/u);
});

test("an unparsable tauri.conf.json is rejected", () => {
  // Обрывок после конфликта слияния не должен читаться как «политика есть».
  const fixture = createFixture();
  fs.writeFileSync(path.join(fixture, "src-tauri", "tauri.conf.json"), '{ "app": { "security": ');

  expectFailure(run(fixture), /Cannot read JSON/u);
});

test("a package.json version that is not SemVer is rejected", () => {
  for (const version of ["0.1", "01.2.3", "v0.1.0"]) {
    expectFailure(runFixture({ version }), /package\.json version is not valid SemVer/u);
  }
});

test("package-lock.json disagreeing with package.json is rejected", () => {
  expectFailure(runFixture({ lockVersion: "0.0.9" }), /package-lock\.json does not match/u);
});

test("package-lock.json root package disagreeing with package.json is rejected", () => {
  // Верхнеуровневый version совпадает, а установленная версия — нет: именно
  // так выглядит недоделанный ручной бамп.
  expectFailure(runFixture({ lockPackageVersion: "0.0.9" }), /package-lock\.json does not match/u);
});

test("Cargo.toml disagreeing with package.json is rejected", () => {
  expectFailure(
    runFixture({
      cargoToml: `[package]\nname = "${PACKAGE_NAME}"\nversion = "0.0.9"\nedition = "2021"\n`,
    }),
    /Cargo version 0\.0\.9 does not match package\.json 0\.1\.0/u,
  );
});

test("a Cargo.toml without a package version is rejected", () => {
  expectFailure(
    runFixture({
      cargoToml: `[package]\nname = "${PACKAGE_NAME}"\nedition = "2021"\n\n[dependencies]\ntauri = { version = "2" }\n`,
    }),
    /Cannot locate \[package\] version/u,
  );
});

test("Cargo.lock disagreeing with package.json is rejected", () => {
  expectFailure(
    runFixture({
      cargoLock: `# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = "${PACKAGE_NAME}"\nversion = "0.0.9"\n`,
    }),
    /Cargo\.lock version 0\.0\.9 does not match/u,
  );
});

test("a Cargo.lock without the application package is rejected", () => {
  expectFailure(
    runFixture({
      cargoLock: `# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = "serde"\nversion = "1.0.0"\n`,
    }),
    /Cannot locate modelcrew-desktop in src-tauri\/Cargo\.lock/u,
  );
});

test("tauri.conf.json pinned to a stale version is rejected", () => {
  expectFailure(
    runFixture({ tauriVersion: "0.0.9" }),
    /tauri\.conf\.json version must be \.\.\/package\.json/u,
  );
});

test("tauri.conf.json may still carry the literal current version", () => {
  expectSuccess(runFixture({ tauriVersion: VERSION }));
});

test("a tag that does not match the application version is rejected", () => {
  expectFailure(
    runFixture({}, ["--tag", "v9.9.9", "--latest-tag", "v0.0.9"]),
    /Tag v9\.9\.9 does not match application version v0\.1\.0/u,
  );
});

test("a tag without the v prefix is rejected", () => {
  expectFailure(
    runFixture({}, ["--tag", "0.1.0", "--latest-tag", "v0.0.9"]),
    /does not match application version v0\.1\.0/u,
  );
});

test("a tag for a pre-release version is rejected by the tag format rule", () => {
  // Версия проходит SemVer, тег совпадает с ней — и всё же выпускать
  // v1.2.3-beta.1 нельзя: обновлятор сравнивает только X.Y.Z.
  const version = "1.2.3-beta.1";
  expectFailure(
    runFixture({ version }, ["--tag", `v${version}`, "--latest-tag", "v0.0.9"]),
    /Release tag has invalid format: v1\.2\.3-beta\.1/u,
  );
});

test("a release that does not move the version forward is rejected", () => {
  const fixture = createFixture();

  for (const latestTag of ["v0.1.0", "v0.2.0", "v1.0.0"]) {
    expectFailure(
      run(fixture, ["--tag", `v${VERSION}`, "--latest-tag", latestTag]),
      /0\.1\.0 must be greater than the latest public release/u,
    );
  }
});

test("an unparsable latest release tag is rejected instead of being ignored", () => {
  // Если сюда попадёт мусор из ответа GitHub, проверка монотонности не
  // должна тихо выключиться.
  expectFailure(
    runFixture({}, ["--tag", `v${VERSION}`, "--latest-tag", "0.0.9"]),
    /Invalid latest release tag: 0\.0\.9/u,
  );
  expectFailure(
    runFixture({}, ["--tag", `v${VERSION}`, "--latest-tag", "vlatest"]),
    /latest public release version is not valid SemVer/u,
  );
});

test("a first public release other than 0.0.1 is rejected", () => {
  expectFailure(
    runFixture({}, ["--tag", `v${VERSION}`]),
    /The first public release must be 0\.0\.1, not 0\.1\.0/u,
  );
  expectSuccess(runFixture({ version: "0.0.1" }, ["--tag", "v0.0.1"]));
});

test("a missing release notes file is rejected", () => {
  expectFailure(runFixture({ notes: null }), /Cannot read JSON[\s\S]*0\.1\.0\.json/u);
});

test("release notes written for another version are rejected", () => {
  expectFailure(
    runFixture({ notes: { ...releaseNotes("0.0.9"), version: "0.0.9" } }),
    /Release notes version 0\.0\.9 does not match 0\.1\.0/u,
  );
});

test("release notes containing markup are rejected", () => {
  // Заметки попадают в окно обновления, поэтому угловые скобки в них не
  // проезжают дальше этой проверки.
  const notes = releaseNotes(VERSION);
  notes.en.highlights = ["<img src=x onerror=alert(1)>"];

  expectFailure(runFixture({ notes }), /cannot contain HTML brackets/u);
});

test("a changelog without a section for the version is rejected", () => {
  expectFailure(
    runFixture({ changelogText: changelog("0.0.1") }),
    /CHANGELOG\.md has no section for 0\.1\.0/u,
  );
});

test("a missing CHANGELOG.md is rejected", () => {
  expectFailure(runFixture({ changelogText: null }), /CHANGELOG\.md/u);
});

test("a changelog section missing the Russian heading is rejected", () => {
  expectFailure(
    runFixture({ changelogText: changelog(VERSION, { ru: false }) }),
    /CHANGELOG\.md 0\.1\.0 must contain Russian and English sections/u,
  );
});

test("a changelog section missing the English heading is rejected", () => {
  expectFailure(
    runFixture({ changelogText: changelog(VERSION, { en: false }) }),
    /CHANGELOG\.md 0\.1\.0 must contain Russian and English sections/u,
  );
});

test("a changelog section that still contains a placeholder is rejected", () => {
  for (const placeholder of ["TODO: написать", "TBD", "PLACEHOLDER", "ЗАПОЛНИТЬ"]) {
    expectFailure(
      runFixture({ changelogText: changelog(VERSION, { body: placeholder }) }),
      /CHANGELOG\.md 0\.1\.0 still contains placeholder text/u,
    );
  }
});

test("a placeholder in a neighbouring section does not block the release", () => {
  const changelogText = `# Changelog\n\n## ${VERSION}\n\n### Русский\n\nРелиз.\n\n### English\n\nRelease.\n\n## 0.0.1\n\nTODO\n`;

  expectSuccess(runFixture({ changelogText }));
});

// Валидатор релиза не смотрит на plugins.updater, поэтому подменённый адрес
// манифеста или чужой публичный ключ прошли бы шлюз незамеченными. Пока этой
// проверки нет в скрипте, значения закреплены здесь.
test("the shipped updater stays pinned to https endpoints and the release key", () => {
  const updater = shippedConfig.plugins.updater;

  assert.ok(Array.isArray(updater.endpoints) && updater.endpoints.length > 0);
  for (const endpoint of updater.endpoints) {
    assert.match(endpoint, /^https:\/\//u, `updater endpoint is not https: ${endpoint}`);
  }
  assert.equal(
    updater.pubkey,
    "dW50cnVzdGVkIGNvbW1lbnQ6IG1pbmlzaWduIHB1YmxpYyBrZXk6IEFENUE2NDg4RjA1NjJDMjIKUldRaUxGYndpR1JhcmViU1V5M1hGVVpUelZydGp2R3F5aWV0Qkh0YU8yTEVTVnlRNGxGZjBOU0sK",
  );
});
